name: hamsFE
description: "Hamster Care IoT App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # cupertino_icons: ^1.0.8
  http: ^1.2.2
  # qr_flutter: ^4.1.0

  # flutter_rating_bar: ^4.0.0
  # shared_preferences: ^2.0.8
  intl: ^0.20.1 # Date formatting
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  web_socket_channel: ^3.0.2
  flutter_local_notifications: ^19.0.0
  image_picker: ^1.1.2
  path: ^1.9.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  permission_handler: ^12.0.0+1
  fl_chart: ^0.71.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
#    - assets/icons/
    - assets/images/