# Air Config
root = "."
tmp_dir = "tmp"
build = "go build -o tmp/main ."
cmd = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "node_modules"]
ignore_dir = ["assets", "public"]
delay = 1000
log = "air.log"
